version: "3.8"
services:
  chroma:
    image: ghcr.io/chroma-core/chroma:0.5.20
    volumes:
      - index_data:/chroma/.chroma/index
    ports:
      - "8000:8000"
    networks:
      - net

volumes:
  index_data:
    driver: local
  backups:
    driver: local

networks:
  net:
    driver: bridge